[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
atrium = "56J6kiYHuu9c1qE3XxhndugKPaqo7oWUNuU5LECBw9UY"

[programs.localnet]
atrium = "56J6kiYHuu9c1qE3XxhndugKPaqo7oWUNuU5LECBw9UY"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
