[toolchain]
anchor_version = "0.32.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
atrium = "GH6m182Lprbfzp4TYwBmTXW3sT6c2ctoF5cyeySRuZkB"

[programs.localnet]
atrium = "GH6m182Lprbfzp4TYwBmTXW3sT6c2ctoF5cyeySRuZkB"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
